# [](fg:#222222)[](fg:#2c2c2c bg:#222222)\
# [](fg:#2c2c2c)\
# $directory\
# [](fg:#2c2c2c)\
# [](fg:#2c2c2c bg:#222222)\
# $git_branch\
# $git_status\
# [](fg:#222222 bg:#2c2c2c)\
# $c\
# $elixir\
# $elm\
# $golang\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# [](fg:#2c2c2c bg:#222222)\
# $docker_context\
# [](fg:#222222)\
# [󰿟 ](fg:#009900)\


format = """

[╭─╴](fg:#555555)\
[](fg:#222222)\
[󰿟](bg:#222222 fg:#007700)\
[█](fg:#222222 )\
$directory\
[█](fg:#222222)\
$git_branch\
$git_status\
[󰿟](bg:#222222 fg:#007700)\
[](fg:#222222)\
[╶](fg:#555555)$fill\

[](fg:#222222)\
[█](fg:#222222)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$docker_context\
$rust\
[█](fg:#222222)\
[](fg:#222222)\
[─╮ ](fg:#555555)
[╰─ ](fg:#555555)\
"""
right_format = """
$kubernetes
[╶╯](fg:#555555)"""


continuation_prompt = "ffffff"
command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false
add_newline = true

[fill]
symbol = '─'
style = 'fg:#555555'

[character]
success_symbol = '[╶─](fg:#555555) '
error_symbol = '[╶](fg:#555555)[✗](bold red)[](fg:#555555) '

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = false
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[$user ]($style)'

[directory]
style = "fg:#990000"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Tech/Images" = "󰗮"
"Tech/CTF" = ""
"Tech/Security" = "󰦝"
"Tech/Hacking" = "󱚝"
"Media/Audio/Music" = ""
"Media/Audio" = ""
"Media/Visual" = "󰺰"
"Projects/Git/Github" =  ""
"Projects/Git/Gitlab" =  ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#222222 fg:#009900"
format = '[ $symbol ($version) ]($style)'

[kubernetes]
format = '[󱃾 ](bold blue)[$context:/](fg:#666666)[$namespace](fg:#006600)'
disabled = false

[docker_context]
symbol = " "
format = "[$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []

[elixir]
symbol = " "
style = "bg:#222222 fg:#009900"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#222222 fg:#009900"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#222222 fg:#009900"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#222222 fg:#999999"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#222222 fg:#009900"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#222222 fg:#009900"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#222222 fg:#009900"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#222222 fg:#009900"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#222222 fg:#009900"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#222222 fg:#009900"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#222222 fg:#009900"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:#222222 fg:#009900"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ $time ]($style)'
