"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
# TOML linter

[manager]
ratio          = [ 0, 4, 4 ]
sort_by        = "natural"
sort_sensitive = false
sort_dir_first = false
linemode       = "none"
show_hidden    = false
show_symlink   = true

[preview]
tab_size        = 2
max_width       = 1600
max_height      = 1900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 2
ueberzug_offset = [ 1, 0, 0, 0 ]

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true,  desc = "Edit", for = "unix" },
]
open = [
	{ run = '$EDITOR "$@"', desc = "Open", for = "linux" },
	{ run = '$HOME/.config/yazi/scripts/ocr $@', block = true, desc = "OCR", for = "unix" },
	{ run = '$HOME/.config/yazi/scripts/qr $@', block = true, desc = "QR", for = "unix" },
	{ run = '$HOME/.config/yazi/scripts/flarestrings $@', block = true, desc = "Strings (Flare)", for = "unix" },
	{ run = '$HOME/.config/yazi/scripts/strings $@', block = true, desc = "Strings", for = "unix" },
	{ run = '$HOME/.config/yazi/scripts/metadata-visual $@', block = true, desc = "Metadata", for = "unix" },
	{ run = 'set-wal "$@"', block = true, desc = "Set Wallpaper", for = "unix" },
	{ run = 'pinta "$@"', block = true, desc = "Edit Image", for = "unix" },
]
reveal = [
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
	{ run = 'unar "$1"', desc = "Extract here", for = "unix" },
]

analyze = [
	{ run = '$HOME/.config/yazi/scripts/encode $@', desc = "Encode", for = "unix" },
	{ run = '$HOME/.config/yazi/scripts/decode $@', desc = "Decode", for = "unix" },
]
image_analysis = [
	{ run = '$HOME/.config/yazi/scripts/ocr $@', desc = "OCR", for = "unix" },
]

play = [
	{ run = "hyprctl dispatch exec \"$TERMINAL -T Terminal --working-directory \\\"$(pwd)\\\" -e /usr/bin/mpv \\\"$@\\\" &>/dev/null & disown\"",  desc = "External mpv", for = "unix" },
]

browser = [
	{ run = '$BROWSER "$@" && hyprctl dispatch workspace 1', block = true, desc = "Open in browser", for = "unix" },
]
pdf = [
	# { run = 'zathura "$@"', desc = "Open PDF", for = "unix" },
]
wireshark = [
	{ run = 'wireshark "$@"', desc = "Open in Wireshark", for = "unix" },
]

[open]
rules = [

	{ mime = "text/html",  use = [ "edit", "reveal", "browser" ] },
	{ mime = "text/*",  use = [ "edit", "reveal" ] },
	{ name = "*.md",  use = [ "edit", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal", "image_analysis" ] },
	{ mime = "video/*", use = [ "play", "reveal" ] },
	{ mime = "audio/*", use = [ "play", "reveal" ] },
	{ mime = "application/pdf", use = [ "pdf" ] },
	{ mime = "inode/x-empty", use = [ "edit", "reveal" ] },

	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript",     use = [ "edit", "reveal" ] },

	{ mime = "application/vnd.tcpdump.pcap", use = [ "wireshark" ] },
	{ name = "*.pcap*",                      use = [ "wireshark" ] },
	{ mime = "application/zip",              use = [ "extract", "reveal" ] },
	{ mime = "application/gzip",             use = [ "extract", "reveal" ] },
	{ mime = "application/x-tar",            use = [ "extract", "reveal" ] },
	{ mime = "application/x-bzip",           use = [ "extract", "reveal" ] },
	{ mime = "application/x-bzip2",          use = [ "extract", "reveal" ] },
	{ mime = "application/x-7z-compressed",  use = [ "extract", "reveal" ] },
	{ mime = "application/x-rar",            use = [ "extract", "reveal" ] },
	{ mime = "application/xz",               use = [ "extract", "reveal" ] },


	{ mime = "*", use = [ "open", "reveal" ] },
	# { mime = "*", use = [ "edit", "open", "reveal", "analyze" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = false

[plugin]

preloaders = [
	# Image
	{ mime = "image/vnd.djvu", run = "noop" },
	{ mime = "image/*",        run = "image" },
	# Video
	{ mime = "video/*", run = "video" },
	# PDF
	{ mime = "application/pdf", run = "pdf" },
	# { name = "*", cond = "!mime", run = "mime", multi = true, prio = "high" },
]
previewers = [
	{ name = "*/", run = "folder", sync = true },
	# Code
	{ mime = "text/*",                 run = "code" },
	{ mime = "*/xml",                  run = "code" },
	{ mime = "*/javascript",           run = "code" },
	{ mime = "*/x-wine-extension-ini", run = "code" },
	# JSON
	{ mime = "application/json", run = "json" },
	# Image
	{ mime = "image/vnd.djvu", run = "noop" },
	{ mime = "image/*",        run = "image" },
	# Video
	{ mime = "video/*", run = "video" },
	# PDF
	{ mime = "application/pdf", run = "pdf" },
	# Archive
	{ mime = "application/zip",             run = "archive" },
	{ mime = "application/gzip",            run = "archive" },
	{ mime = "application/x-tar",           run = "archive" },
	{ mime = "application/x-bzip",          run = "archive" },
	{ mime = "application/x-bzip2",         run = "archive" },
	{ mime = "application/x-7z-compressed", run = "archive" },
	{ mime = "application/x-rar",           run = "archive" },
	{ mime = "application/xz",              run = "archive" },
	# Fallback
	{ name = "*", run = "file" },
]

[input]
# cd
cd_title  = "Change directory:"
cd_origin = "top-center"
cd_offset = [ 0, 2, 50, 3 ]

# create
create_title  = "Create:"
create_origin = "top-center"
create_offset = [ 0, 2, 50, 3 ]

# rename
rename_title  = "Rename:"
rename_origin = "hovered"
rename_offset = [ 0, 1, 50, 3 ]

# trash
trash_title 	= "Move {n} selected file{s} to trash? (y/N)"
trash_origin	= "top-center"
trash_offset	= [ 0, 2, 50, 3 ]

# delete
delete_title 	= "Delete {n} selected file{s} permanently? (y/N)"
delete_origin	= "top-center"
delete_offset	= [ 0, 2, 50, 3 ]

# filter
filter_title  = "Filter:"
filter_origin = "top-center"
filter_offset = [ 0, 2, 50, 3 ]

# find
find_title  = [ "Find next:", "Find previous:" ]
find_origin = "top-center"
find_offset = [ 0, 2, 50, 3 ]

# search
search_title  = "Search via {n}:"
search_origin = "top-center"
search_offset = [ 0, 2, 50, 3 ]

# shell
shell_title  = [ "Shell:", "Shell (block):" ]
shell_origin = "top-center"
shell_offset = [ 0, 2, 50, 3 ]

# overwrite
overwrite_title  = "Overwrite an existing file? (y/N)"
overwrite_origin = "top-center"
overwrite_offset = [ 0, 2, 50, 3 ]

# quit
quit_title  = "{n} task{s} running, sure to quit? (y/N)"
quit_origin = "top-center"
quit_offset = [ 0, 2, 50, 3 ]

[select]
open_title  = "Open with:"
open_origin = "hovered"
open_offset = [ 0, 1, 50, 7 ]

[log]
enabled = false
