#!/usr/bin/env sh
#
test -z "$1" && cd "$1"

tmp="$(mktemp -t "yazi-cwd.XXXXX")"
yazi "$@" --cwd-file="$tmp"
if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
    cd -- "$cwd"
fi
rm -f -- "$tmp"

$SHELL
