#!/usr/bin/env bash
#===========>>
# 
# A script to clear terminal and rerun any command loop gets
#
#===========>>

[[ -z $1 ]] && echo "Error: No command supplied." &&  exit 1

interval=1

[[ -z $2 ]] || interval=$2

while true
do 
  clear
  $1
  sleep $interval
done

